extern  void fatal(char *message);
extern  void dos_fatal( int errnum );
extern  void z_exit( int ecode );
extern  int do_error(int dev_header, int pax,int pdi);
extern  void md_erase_char(void );
extern  void md_sound(char id);
extern  void md_putc( unsigned char c);
extern  void ega_putc( char c );
extern  void mcga_putc(char c);
extern  void cga_putc( char c );
extern  char huge *halloc(unsigned int pages);
extern  char huge *my_halloc(unsigned int paragraphs);
extern  void hfree(char huge *ptr);
extern  int md_msize(int memasked);
extern  int md_find_printer(void );
extern  char *printer_defunct(int prtstat);
extern  void md_close_script(int fd);
extern  void md_script_char(char ch);
extern  int handle_printer_error(char *str);
extern  void md_script_cr(void );
extern  void md_set_color(int fg,int bg, int id);
extern  int md_set_font(int fontno,int id);
extern  long cdecl lseek(int handle,long offset,int type);
extern  void get_disk_info(void );
extern  int get_disk_type(int drive);
extern  int get_fname_drive(char *fname);
extern  void md_display_default(char *fname,char *oname);
extern  void md_install_default(char *fname,char *target);
extern  int md_parse_file(char *usrnam,char *outnam,char *defnam);
extern  void md_check_swap(char *fname);
extern  void md_check_unswap(void );
extern  void md_get_game_chan(int force);
extern  void scroll(int id,int linz);
extern  void winpos(int id,int y,int x);
extern  void winsize(int id,int y,int x);
extern  void winattr(int id,int bits,int operation);
extern  void curset(int y,int x,int id);
extern  int winget(int id,int offset);
extern  void winput( int id, int which1, int newval);
extern  void _setargv(void );
extern  void _setenvp(void );
extern  void _nullcheck(void );
extern  int init( char *name );
extern  void sysini(void );
extern  void memini(void );
extern  void centerprt(char *str,int lin);
extern  void copyright(void );
extern  void zipini(void );
extern  void restart(int midgame);
extern  long filen(int fd);
extern  char lc(char ch);
extern  void xpush(int value,unsigned short stack);
extern  void pop(unsigned short stack);
extern  void fstack(int val,unsigned short stack);
extern  void mouse_info(unsigned short tabl);
extern  void mouse_lim(int id);
extern  void wind_init(void );
extern  int internal_sav_res(int fcn);
extern  void picinf(int picture,unsigned short data);
extern  void disp_pic(int pict,int y,int x);
extern  long tlseek(int handle,long offset,int type);
extern  void load_palette( void );
extern	void reopen_pic_file( void );
extern	int open_picfile( char *name, int id );
extern  void open_picture_file(char *game,int fid);
extern  unsigned short *do_binary_search(unsigned short *dir,int len,int de_size,int id);
extern  int get_dir_entry( int id );
extern  struct PF_LOCAL_DIR *find_pic_id( int id );
extern  int search_global_dir(int id);
extern  void disp_pic_f( unsigned int x, unsigned int y, unsigned int width, unsigned int height, unsigned int rx, unsigned int ry,
unsigned int handle, unsigned char transparent );
extern  void set_dacreg(int strt_color,int amt_clrs,char *ptr_to_clrbuf);
extern  void run_zero_op( unsigned char operand );
extern  void run_one_op( unsigned char operand );
extern  void run_two_op(unsigned char operand);
extern  int find_prop( short object, ZIPBYT property, ZIPBYT *lastp );
extern  void get_ext_args(unsigned short opcode);
extern  void run_ext_op(unsigned short opcode);
extern  void do_seek(int fd,int how,int where);
extern  int md_mouse(int fcn, ... );
extern  void md_write_cursor(int state);
extern  void colorq(void );
extern  int scan_copyright(unsigned char far *ptr,unsigned char *str);
extern  void md_check_display( void );
extern  void md_set_display( void );
extern  void md_init_color( void );
extern  void md_init_screen( void );
extern  void md_init_stuff( void );
extern  void md_install_fonts( void );
extern  void md_check_display( void );
extern  void md_set_display( void );
extern  void md_ttyres(void );
extern  int md_getch(void );
extern  unsigned char md_cvtchr(int chr);
extern  int md_inp(void );
extern  int md_tinp(unsigned short time,unsigned short handler);
extern  void md_hlite(unsigned short attrib);
extern  void md_setup(void );
extern  void mtime(void );
extern  int cdecl rand(void );
extern  void md_clr(int scrno);
extern  void clear_area( int top, int left, int width, int height );
extern  void clear_screen(void );
extern  void home( struct WINDOW *wptr );
extern  void locate(short row,short col);
extern  void md_mcrlf(void );
extern  void mcrlf(void );
extern  void md_clear_eol(void );
extern  void md_printstr(char *str);
extern  void md_outstr(char *str);
extern  long get_time(void );
extern  void md_inittime(void );
extern  int md_time_diff(long itime);
extern  void md_wait(int secs);
extern  int md_timed_out(void );
extern  int md_getl(char *buf,int cnt,int i,int timeout, unsigned short timer);
extern  int zread(void );
extern  void zlex(unsigned short inbuf,unsigned short lexv,unsigned short lexicon,unsigned short preserve);
extern  int zwstr(unsigned short inbuf,short length, short inbeg,unsigned short zword);
extern  int notbrkc(char c);
extern  int char_cs(char c);
extern  char chrbyt(char c);
extern  unsigned short lookup(unsigned short lexicon);
extern  int getlin(short buffer,unsigned short timeout,short timerout);
extern  void flushwrds(char huge *strbeg,short stroff,short strlen);
extern  char do_mouse_event(int *tab);
extern  void yzipvers(void );
extern  void getpre(short first,short final);
extern  void getblk(short block,char huge *loc);
extern  int wrtbyts(char huge *loc,unsigned int numbyts);
extern  int rdbyts(char huge *loc,unsigned int numbyts);
extern  void putstr(void );
extern  int getzchr(unsigned short zchr,unsigned short charset);
extern  void putchr(unsigned short letter);
extern  void cr_int(void );
extern  void newlin(void );
extern  void dumpbuf(void );
extern  void print_number(int num, void (*prtfunc)());
extern  void errprnt(char *buf);
extern  void gamprnt(char *buf);
extern  void script_string(char *buf);
extern  void script_input(unsigned short ibuf);
extern  void mprnt(char *buf);
extern  void zmprnt(char huge *buf);
extern  void chkscript(void );
extern  void flush_buffer(void );
extern  int not_terminator(unsigned char c);
extern  void script_off(void );
extern  void ftblprnt(void );
extern  void put_to_screen(unsigned short letter);
extern  void prt_tblf(unsigned short tbl);
extern  void get_ext_args(unsigned short opcode);
extern  void run_ext_op(unsigned short opcode);
extern  void domargin(int lmarg,int rmarg,int id);
extern  void dorand(void );
extern  void dodirout(int ab1,unsigned short ab2,int ab3, int formflag);
extern  void dosplit(int lin);
extern  void newdoscreen(int id);
extern  void main_loop(void );
extern  void zremove(unsigned short obj);
extern  void printi(void );
extern  void printd(unsigned short obj);
extern  void zret(unsigned short rtval);
extern  char huge *objloc(unsigned short obj);
extern  unsigned short firstprp(unsigned short obj);
extern  unsigned short nxtprp(unsigned short propoff);
extern  char huge *flagptr(unsigned short obj,unsigned short *flagnum);
extern  short getarg(char mode);
extern  ZIPINT getvar(unsigned char var);
extern  void putvar(unsigned char var,short value);
extern  void putval(short value);
extern  void bytval(unsigned char value);
extern  void ppred(unsigned short truth);
extern  void dobreak(void );
extern  void docall( ZIPINT retval );
extern  int internal_call(short rout);
extern  void do_throw(unsigned short rval,unsigned short frame);
extern  void globals_to_window(int id);
extern  void window_to_globals(int id);
extern  void PTAWRD(char huge *ptr,unsigned short value);
extern  unsigned short nxtwrd(void );
extern  unsigned short purwrd(unsigned short blk,unsigned short off);
extern  unsigned short datwrd(unsigned int addr);
extern  unsigned char datbyt(unsigned int addr);
extern  unsigned char getbyt(void );
extern  unsigned short getwrd(void );
extern  void newzpc(void );
extern  char huge *getpag(short blk);
extern  void unlinkb(short block);
extern  void relinkb(short block);
extern  void bspltb(unsigned short bytaddr);
extern  void bspltb2(long bytaddr);
extern  void bsplit(unsigned short wrdaddr);
extern  void bsplitq(unsigned short quadaddr);
extern  void bsplitq2(long quadaddr);
extern  void bsplito(unsigned short octaddr);
extern  void bsplitqy(long octaddr);
extern  int internal_sav_res(int fcn);
extern  void save_screen_stuff(unsigned short *scrsave);
extern  void restore_screen_stuff(unsigned short *scrsave);
extern  void push_save_stuff(void );
extern  int pop_save_stuff(int pc_change);
extern  int partial_sav_res(int fcn,int start,int length,int name);
extern  int same_name(char *buf,char *file,int len);
extern  int sav_res(int fcn);
extern  void do_delete(char *str);
extern  int verify(void );
extern  unsigned short blocksum(unsigned char *buffer,short block,short off1,short off2);
extern  void valid_curs( struct WINDOW *wptr );
extern  void split_valid_curs( struct WINDOW *wptr );
extern  int get_pixel_color( int x, int y );
extern  void md_erase( int pixcnt );

/* ASM declarations */
extern  unsigned far_read( int fd, unsigned seg, unsigned off, unsigned req );
extern  unsigned far_write( int fd, unsigned seg, unsigned off, unsigned req );
extern  void PTVWRD( int offset, int value );
extern  int get_mouse_event( int *table );
extern  int GTVWRD( int offset );
extern  int GTAWRD( char huge *offset );
extern  int zopen( char *filename, int mode );
extern  int zcreat( char *filename );
extern  int zclose( int handle );
extern  unsigned char nxtbyt( void );
extern  void do_copy( unsigned start, unsigned end, unsigned seg, unsigned off, int amount );
extern  void do_intbl( unsigned item, unsigned table, unsigned len, unsigned recspec );
extern  void do_table_copy( unsigned src, unsigned dest, unsigned len );
extern  void do_table_print( unsigned table, unsigned width, unsigned height, unsigned dunno );
extern  unsigned get_segreg( int which1 );
extern  void zdumpfont( char *font );
extern  void zusrfont( char *font );
extern  int int86( int intno, union REGS *inreg, union REGS *outreg );
extern  int int86x( int intno, union REGS *inreg, union REGS *outreg, int seg, int segr );
extern  int display_char13( int ch, int width, int monospaced );
extern  int display_char10( int ch );
extern  int display_char06( int ch );
extern  void mcga_scroll( int lx, int ty, int width, int height, int nlines, int back );
extern  void ega_scroll( int lx, int ty, int width, int height, int nlines, int back );
extern  void iscroll( int lx, int ty, int width, int height, int nlines, int back );
